/**
 * chat 自动标题生成（maybeGenerateChatTitle）单测
 *
 * mock @cursor/sdk Agent.prompt + task-fs 读写，覆盖：
 * pending 真 → 调 prompt 写回；pending 假跳过；生成中用户改名不覆盖；
 * 抛错/空结果不写；引号与超长清洗。
 */
import { afterEach, describe, expect, it, vi } from "vitest";

import type { Task } from "@/lib/types";

const mockPrompt = vi.fn();
vi.mock("@cursor/sdk", () => ({
  Agent: {
    prompt: (...args: unknown[]) => mockPrompt(...args),
  },
}));

const mockGetTask = vi.fn();
const mockCommit = vi.fn();
const mockUpdateFields = vi.fn();
const mockPublish = vi.fn();

vi.mock("@/lib/server/task-fs", () => ({
  getTask: (...args: unknown[]) => mockGetTask(...args),
  commitAutoGeneratedChatTitle: (...args: unknown[]) => mockCommit(...args),
  updateTaskFields: (...args: unknown[]) => mockUpdateFields(...args),
}));

vi.mock("@/lib/server/task-stream", () => ({
  publish: (...args: unknown[]) => mockPublish(...args),
}));

const { maybeGenerateChatTitle, sanitizeGeneratedChatTitle } = await import(
  "@/lib/server/chat-title"
);

const baseTask = (over: Partial<Task> = {}): Task =>
  ({
    id: "t-chat-1",
    title: "对话 · 07-21 15:00",
    titleAutoPending: true,
    mode: "chat",
    repoStatus: "developing",
    runStatus: "running",
    currentActionId: null,
    actions: [],
    mrs: [],
    repoPaths: [],
    createdAt: 1,
    updatedAt: 1,
    events: [],
    ...over,
  }) as Task;

/** 等到 mock 被调到（fire-and-forget 内部 async） */
const waitUntil = async (
  pred: () => boolean,
  timeoutMs = 2000,
): Promise<void> => {
  const start = Date.now();
  while (!pred()) {
    if (Date.now() - start > timeoutMs) {
      throw new Error("waitUntil timeout");
    }
    await new Promise((r) => setTimeout(r, 10));
  }
};

afterEach(() => {
  mockPrompt.mockReset();
  mockGetTask.mockReset();
  mockCommit.mockReset();
  mockUpdateFields.mockReset();
  mockPublish.mockReset();
});

describe("sanitizeGeneratedChatTitle", () => {
  it("剥首尾引号并截断超长", () => {
    expect(sanitizeGeneratedChatTitle('  "修复登录 bug"  ')).toBe(
      "修复登录 bug",
    );
    const long = "一二三四五六七八九十一二三四五六七八九十一二三四五六";
    expect(long.length).toBeGreaterThan(24);
    expect(sanitizeGeneratedChatTitle(`「${long}」`)).toBe(long.slice(0, 24));
    expect(sanitizeGeneratedChatTitle("   ")).toBeNull();
    expect(sanitizeGeneratedChatTitle("标题。")).toBe("标题");
  });
});

describe("maybeGenerateChatTitle", () => {
  it("titleAutoPending=true → 调 prompt、清洗后写回标题并清 pending", async () => {
    mockGetTask.mockResolvedValue(baseTask());
    mockPrompt.mockResolvedValue({
      id: "run-1",
      status: "finished",
      result: "「修登录态」",
    });
    const committed = baseTask({
      title: "修登录态",
      titleAutoPending: undefined,
    });
    mockCommit.mockResolvedValue(committed);

    maybeGenerateChatTitle("t-chat-1", "key-x", "帮我修一下登录态过期的问题");
    await waitUntil(() => mockPublish.mock.calls.length > 0);

    expect(mockPrompt).toHaveBeenCalledTimes(1);
    const [promptText, opts] = mockPrompt.mock.calls[0]!;
    expect(String(promptText)).toContain("帮我修一下登录态过期的问题");
    expect(String(promptText)).toContain("不超过 12 个字");
    expect(opts).toMatchObject({
      apiKey: "key-x",
      model: { id: "auto" },
      mcpServers: {},
      local: { settingSources: [] },
    });
    expect(mockCommit).toHaveBeenCalledWith("t-chat-1", "修登录态");
    expect(mockPublish).toHaveBeenCalledWith("t-chat-1", {
      kind: "task",
      task: committed,
    });
  });

  it("titleAutoPending 缺失/false → 不调 prompt", async () => {
    mockGetTask.mockResolvedValue(
      baseTask({ titleAutoPending: undefined }),
    );
    maybeGenerateChatTitle("t-chat-1", "key-x", "你好");
    await waitUntil(() => mockGetTask.mock.calls.length >= 1);
    // 再给一点时间确认 prompt 不会被调
    await new Promise((r) => setTimeout(r, 30));
    expect(mockPrompt).not.toHaveBeenCalled();
    expect(mockCommit).not.toHaveBeenCalled();

    mockGetTask.mockResolvedValue(baseTask({ titleAutoPending: false }));
    maybeGenerateChatTitle("t-chat-1", "key-x", "你好");
    await waitUntil(() => mockGetTask.mock.calls.length >= 2);
    await new Promise((r) => setTimeout(r, 30));
    expect(mockPrompt).not.toHaveBeenCalled();
  });

  it("生成期间用户改名（第二次读 pending 已 false）→ 不覆盖", async () => {
    mockGetTask.mockResolvedValue(baseTask());
    mockPrompt.mockResolvedValue({
      id: "run-1",
      status: "finished",
      result: "自动标题",
    });
    // commit 锁内复查失败 → null
    mockCommit.mockResolvedValue(null);

    maybeGenerateChatTitle("t-chat-1", "key-x", "首条消息");
    await waitUntil(() => mockCommit.mock.calls.length > 0);

    expect(mockPrompt).toHaveBeenCalledTimes(1);
    expect(mockCommit).toHaveBeenCalledWith("t-chat-1", "自动标题");
    expect(mockPublish).not.toHaveBeenCalled();
  });

  it("prompt 抛错 / 返回空 → 不写标题、不抛", async () => {
    mockGetTask.mockResolvedValue(baseTask());
    mockPrompt.mockRejectedValue(new Error("sdk down"));

    expect(() =>
      maybeGenerateChatTitle("t-chat-1", "key-x", "首条"),
    ).not.toThrow();
    await waitUntil(() => mockPrompt.mock.calls.length >= 1);
    await new Promise((r) => setTimeout(r, 30));
    expect(mockCommit).not.toHaveBeenCalled();

    mockPrompt.mockResolvedValue({
      id: "run-2",
      status: "finished",
      result: "   ",
    });
    maybeGenerateChatTitle("t-chat-1", "key-x", "首条");
    await waitUntil(() => mockPrompt.mock.calls.length >= 2);
    await new Promise((r) => setTimeout(r, 30));
    expect(mockCommit).not.toHaveBeenCalled();
  });

  it("结果带引号/超长 → 清洗截断正确", async () => {
    mockGetTask.mockResolvedValue(baseTask());
    const long = "一二三四五六七八九十一二三四五六七八九十一二三四五六";
    expect(long.length).toBeGreaterThan(24);
    mockPrompt.mockResolvedValue({
      id: "run-3",
      status: "finished",
      result: `"${long}"`,
    });
    mockCommit.mockResolvedValue(
      baseTask({ title: long.slice(0, 24), titleAutoPending: undefined }),
    );

    maybeGenerateChatTitle("t-chat-1", "key-x", "长文");
    await waitUntil(() => mockCommit.mock.calls.length > 0);

    expect(mockCommit).toHaveBeenCalledWith("t-chat-1", long.slice(0, 24));
  });
});
