/**
 * chat 对话标题自动生成（首轮后用 SDK auto 模型、尽可能少 token）
 *
 * 挂点：runChatSession 里 agent.send 成功返回后 fire-and-forget。
 * apiKey 搭车客户端每次 run 传入的链（server 不持久化 key）。
 *
 * 幂等：靠 task.titleAutoPending——缺失 / false 直接跳过；写回前锁内再查一次，
 * 避免用户中途手动改名后被覆盖。
 */

import { promises as fs } from "node:fs";
import os from "node:os";
import path from "node:path";

import { Agent } from "@cursor/sdk";

import {
  commitAutoGeneratedChatTitle,
  getTask,
  updateTaskFields,
} from "./task-fs";
import { publish } from "./task-stream";

/** Agent.prompt 挂起上限——超时放弃，标题保留占位 / 截断默认 */
const TITLE_GEN_TIMEOUT_MS = 30_000;

/** 送进模型的用户原文上限（省 input token） */
const FIRST_MESSAGE_MAX_CHARS = 500;

/** 写回标题硬上限（侧栏窄、CJK 约一屏宽） */
const TITLE_MAX_CHARS = 24;

/**
 * 清洗模型输出：trim、剥首尾引号、截断。空串返 null（调用方放弃写盘）。
 * 导出供单测覆盖引号 / 超长边界。
 */
export const sanitizeGeneratedChatTitle = (raw: string): string | null => {
  let t = raw.trim();
  // 模型爱加「」""''——剥一层首尾对称引号
  if (
    (t.startsWith("「") && t.endsWith("」")) ||
    (t.startsWith("『") && t.endsWith("』")) ||
    (t.startsWith('"') && t.endsWith('"')) ||
    (t.startsWith("'") && t.endsWith("'")) ||
    (t.startsWith("“") && t.endsWith("”")) ||
    (t.startsWith("‘") && t.endsWith("’"))
  ) {
    t = t.slice(1, -1).trim();
  }
  // 去掉末尾句号类标点（prompt 已禁、模型偶尔仍加）
  t = t.replace(/[。.!！?？]+$/u, "").trim();
  if (!t) return null;
  if (t.length > TITLE_MAX_CHARS) t = t.slice(0, TITLE_MAX_CHARS);
  return t;
};

const buildTitlePrompt = (firstMessage: string): string => {
  const clipped =
    firstMessage.length > FIRST_MESSAGE_MAX_CHARS
      ? firstMessage.slice(0, FIRST_MESSAGE_MAX_CHARS)
      : firstMessage;
  // 极简 prompt：指令短 + 原文截断，省 token；禁工具靠文案约束（SDK 无 maxTokens / 禁工具开关）
  return (
    `${clipped}\n\n` +
    `为这段对话生成一个不超过 12 个字的中文标题。直接输出标题本身，不要引号、不要标点结尾、不要使用任何工具。`
  );
};

type PromptOutcome =
  | { kind: "ok"; text: string }
  | { kind: "empty" }
  | { kind: "timeout" };

/**
 * 超时 race：Agent.prompt 挂死时 30s 放弃，不让 fire-and-forget 永久占着。
 * 区分 timeout / 空结果——空不写标题但也不误清 pending 成「超时放弃」。
 */
const promptWithTimeout = async (
  prompt: string,
  apiKey: string,
): Promise<PromptOutcome> => {
  let timer: ReturnType<typeof setTimeout> | undefined;
  // 每次 mkdtemp 新建专用空目录当 cwd（2026-07-21 用户拍板）：共享系统 tmp 里可能
  // 躺着别的大文件、模型手痒去读会白烧 token——空目录里无物可读
  const emptyCwd = await fs.mkdtemp(path.join(os.tmpdir(), "flowship-title-"));
  try {
    const result = await Promise.race([
      Agent.prompt(prompt, {
        apiKey,
        model: { id: "auto" },
        // settingSources=[]：不加载 user/project rules
        // mcpServers={}：不挂任何 MCP，进一步压工具面
        local: { cwd: emptyCwd, settingSources: [] },
        mcpServers: {},
      }),
      new Promise<"timeout">((resolve) => {
        timer = setTimeout(() => resolve("timeout"), TITLE_GEN_TIMEOUT_MS);
      }),
    ]);
    if (result === "timeout") return { kind: "timeout" };
    const raw = typeof result.result === "string" ? result.result : "";
    return raw.trim() ? { kind: "ok", text: raw } : { kind: "empty" };
  } finally {
    if (timer) clearTimeout(timer);
    // 清理临时空目录（超时路径 Agent 可能还占着——force 容忍）
    void fs.rm(emptyCwd, { recursive: true, force: true }).catch(() => {});
  }
};

const runGenerateChatTitle = async (
  taskId: string,
  apiKey: string,
  firstMessage: string,
): Promise<void> => {
  const task = await getTask(taskId);
  if (!task || task.titleAutoPending !== true) return;

  const text = firstMessage.trim();
  if (!text) return;

  let outcome: PromptOutcome;
  try {
    outcome = await promptWithTimeout(buildTitlePrompt(text), apiKey);
  } catch (err) {
    console.warn(
      `[chat-title] Agent.prompt 失败 task=${taskId}:`,
      err instanceof Error ? err.message : err,
    );
    return;
  }

  // 超时：清 pending 放弃（简单起见不重试；标题保持占位 / 首条截断）
  if (outcome.kind === "timeout") {
    console.warn(`[chat-title] 生成超时放弃 task=${taskId}`);
    const cleared = await updateTaskFields(taskId, {
      titleAutoPending: false,
    });
    if (cleared) publish(taskId, { kind: "task", task: cleared });
    return;
  }
  if (outcome.kind === "empty") return;

  const cleaned = sanitizeGeneratedChatTitle(outcome.text);
  if (!cleaned) return;

  // 锁内复查 pending——用户可能已手动改名
  const updated = await commitAutoGeneratedChatTitle(taskId, cleaned);
  if (updated) publish(taskId, { kind: "task", task: updated });
};

/**
 * fire-and-forget：内部 async 全链 try/catch，绝不抛到调用方。
 */
export const maybeGenerateChatTitle = (
  taskId: string,
  apiKey: string,
  firstMessage: string,
): void => {
  void runGenerateChatTitle(taskId, apiKey, firstMessage).catch((err) => {
    console.warn(
      `[chat-title] 未捕获异常 task=${taskId}:`,
      err instanceof Error ? err.message : err,
    );
  });
};
